### ISSUE TITLE
Splay hulls checklist

### ISSUE THREAD

**Issue by jedwards1211** [jedwards1211/breakout#75]
- [ ] remove triangles that are too skinny for float precision
- [ ] fix mesh builder hash collision risk
- [ ] fix internal wireframe issue / add wireframe toggle to UI?

**Comment by jedwards1211** [comment]
done
